### ISSUE TITLE
crypto.Signer error while running go get

### ISSUE THREAD

**Issue by mcstafford-git** [tillberg/gut#10]
I don't have experience troubleshooting go. Can you point me in the right direction here?

Thanks.

$ `go version`
go version go1.2.1 linux/amd64

$ `echo $GOPATH`
GOPATH=/home/username-goes-here/go

$ `uname -a`
Linux hostname-goes-here 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

`$ go get github.com/tillberg/gut`
# golang.org/x/crypto/ssh
src/golang.org/x/crypto/ssh/keys.go:492: undefined: crypto.Signer

$ `cat -n $GOPATH/src/golang.org/x/crypto/ssh/keys.go | head -n 495 | tail -n 6`

``` 490
   491  type wrappedSigner struct {
   492      signer crypto.Signer
   493      pubKey PublicKey
   494  }
   495
```

**Comment by tillberg** [comment]
I think the Go compiler you have installed might be a bit out of date. I googled and found another issue where someone encountered a similar error with the crypto package that was fixed by upgrading from 1.3 to 1.4.2: https://github.com/cloudflare/cfssl/issues/144.
