### ISSUE TITLE
What is shasum

### ISSUE THREAD

**Issue by thdxr** [tillberg/gut#13]
Gut attempts to run shasum which I'm having difficulty finding documentation for. I do shave sha256sum installed

**Comment by tillberg** [comment]
`shasum` is a utility that at least ships with ubuntu -- http://manpages.ubuntu.com/manpages/intrepid/man1/shasum.1p.html

I figured it was some sort of standard program when I used it, but that's not true, and it does need to be fixed to work across a wider array of systems -- I don't even use Ubuntu myself anymore.

You should be able to bypass that by adding the `--build-deps` flag when invoking gut, I think, though.

**Comment by thdxr** [comment]
Great thanks managed to find it in perl binaries.
